update dates
CornellDataScience/info1998 pull request #1
Opened 2019-09-19 14:45 UTC by yangdanny97

the website still says 2018 dates and locations which will confuse students. i've brought this up for a while now and no one has changed it, so here is a pull request that removes the inaccurate info. we can update the site once there is accurate info

2019-09-19 19:53 UTC, JunyoungLim requested changes

2019-09-19 19:53 UTC, JunyoungLim commented on syllabus.md
> +TBD
Let's add the names of the instructor and TA's without OH information:
```suggestion
**Lecturer: Tanmay Bansal**
- Office Hour TBD
```

2019-09-19 19:53 UTC, JunyoungLim commented on syllabus.md
```suggestion
**TA: Ang Jia Jiunn**
- Office Hour TBD

**TA: Camilo Cedeno-Tobon**
- Office Hour TBD

**TA: Chris Elliott**
- Office Hour TBD

**TA: Dylan Tsai**
- Office Hour TBD

**TA: Samantha Cobado**
- Office Hour TBD
```

2019-09-19 20:01 UTC, JunyoungLim commented
Also, we should change the information in `_config.yml` file to reflect the date change. If you can, please do so, if not, I can quickly do it after merging this PR.

2019-09-19 21:02 UTC, yangdanny97 commented
addressed changes

2019-09-20 19:32 UTC, JunyoungLim approved these changes

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +Location location: Kennedy B-11
```suggestion
Location: Kimball B11
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
- Thursday: 3:30pm - 4:30pm, Rhodes 503
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
Thursday: 2:00pm - 3:00pm, Rhodes 503
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
Tuesday: 3:00pm - 4:00pm, Rhodes 503
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
Wednesday: 2:00pm - 3:00pm, Rhodes 503
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
Wednesday: 2:00pm - 3:00pm, Rhodes 503
```

2019-09-20 19:32 UTC, JunyoungLim commented on syllabus.md
> +- Office Hour TBD
```suggestion
Thursday: 6:00pm - 7:00pm, Rhodes 503
```

2019-09-20 19:45 UTC, merged